# Generated by Django 4.2 on 2026-06-01 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=50, unique=True)),
                ('asset_name', models.CharField(max_length=100)),
                ('asset_type', models.CharField(max_length=50)),
                ('assigned_to', models.CharField(max_length=100)),
                ('status', models.CharField(default='Available', max_length=20)),
            ],
        ),
    ]
