# Generated by Django 6.0.6 on 2026-06-10 05:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='assigned_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='AssetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_by', models.CharField(max_length=100)),
                ('change_type', models.CharField(max_length=50)),
                ('field_changed', models.CharField(blank=True, max_length=50)),
                ('old_value', models.CharField(blank=True, max_length=200)),
                ('new_value', models.CharField(blank=True, max_length=200)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='assets.asset')),
            ],
            options={
                'verbose_name_plural': 'Asset histories',
                'ordering': ['-changed_at'],
            },
        ),
    ]
